// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file vehicle_alert.proto (package telemetry.vehicle_alerts, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file vehicle_alert.proto.
 */
export const file_vehicle_alert: GenFile = /*@__PURE__*/
  fileDesc("ChN2ZWhpY2xlX2FsZXJ0LnByb3RvEhh0ZWxlbWV0cnkudmVoaWNsZV9hbGVydHMihAEKDVZlaGljbGVBbGVydHMSNgoGYWxlcnRzGAEgAygLMiYudGVsZW1ldHJ5LnZlaGljbGVfYWxlcnRzLlZlaGljbGVBbGVydBIuCgpjcmVhdGVkX2F0GAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBILCgN2aW4YAyABKAkisQEKDFZlaGljbGVBbGVydBIMCgRuYW1lGAEgASgJEjUKCWF1ZGllbmNlcxgCIAMoDjIiLnRlbGVtZXRyeS52ZWhpY2xlX2FsZXJ0cy5BdWRpZW5jZRIuCgpzdGFydGVkX2F0GAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIsCghlbmRlZF9hdBgEIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAqQgoIQXVkaWVuY2USCwoHVW5rbm93bhAAEgwKCEN1c3RvbWVyEAESCwoHU2VydmljZRACEg4KClNlcnZpY2VGaXgQA0IvWi1naXRodWIuY29tL3Rlc2xhbW90b3JzL2ZsZWV0LXRlbGVtZXRyeS9wcm90b3NiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * VehicleAlerts is a collection of recent alerts.
 *
 * @generated from message telemetry.vehicle_alerts.VehicleAlerts
 */
export type VehicleAlerts = Message<"telemetry.vehicle_alerts.VehicleAlerts"> & {
  /**
   * @generated from field: repeated telemetry.vehicle_alerts.VehicleAlert alerts = 1;
   */
  alerts: VehicleAlert[];

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 2;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: string vin = 3;
   */
  vin: string;
};

/**
 * Describes the message telemetry.vehicle_alerts.VehicleAlerts.
 * Use `create(VehicleAlertsSchema)` to create a new message.
 */
export const VehicleAlertsSchema: GenMessage<VehicleAlerts> = /*@__PURE__*/
  messageDesc(file_vehicle_alert, 0);

/**
 * VehicleAlert is a single alert and is active if ended_at is nil.
 *
 * @generated from message telemetry.vehicle_alerts.VehicleAlert
 */
export type VehicleAlert = Message<"telemetry.vehicle_alerts.VehicleAlert"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: repeated telemetry.vehicle_alerts.Audience audiences = 2;
   */
  audiences: Audience[];

  /**
   * @generated from field: google.protobuf.Timestamp started_at = 3;
   */
  startedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp ended_at = 4;
   */
  endedAt?: Timestamp;
};

/**
 * Describes the message telemetry.vehicle_alerts.VehicleAlert.
 * Use `create(VehicleAlertSchema)` to create a new message.
 */
export const VehicleAlertSchema: GenMessage<VehicleAlert> = /*@__PURE__*/
  messageDesc(file_vehicle_alert, 1);

/**
 * Audience the target audience for the alert.
 *
 * @generated from enum telemetry.vehicle_alerts.Audience
 */
export enum Audience {
  /**
   * @generated from enum value: Unknown = 0;
   */
  Unknown = 0,

  /**
   * @generated from enum value: Customer = 1;
   */
  Customer = 1,

  /**
   * @generated from enum value: Service = 2;
   */
  Service = 2,

  /**
   * @generated from enum value: ServiceFix = 3;
   */
  ServiceFix = 3,
}

/**
 * Describes the enum telemetry.vehicle_alerts.Audience.
 */
export const AudienceSchema: GenEnum<Audience> = /*@__PURE__*/
  enumDesc(file_vehicle_alert, 0);

