// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file vehicle_connectivity.proto (package telemetry.vehicle_connectivity, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file vehicle_connectivity.proto.
 */
export const file_vehicle_connectivity: GenFile = /*@__PURE__*/
  fileDesc("Chp2ZWhpY2xlX2Nvbm5lY3Rpdml0eS5wcm90bxIedGVsZW1ldHJ5LnZlaGljbGVfY29ubmVjdGl2aXR5IscBChNWZWhpY2xlQ29ubmVjdGl2aXR5EgsKA3ZpbhgBIAEoCRIVCg1jb25uZWN0aW9uX2lkGAIgASgJEkEKBnN0YXR1cxgDIAEoDjIxLnRlbGVtZXRyeS52ZWhpY2xlX2Nvbm5lY3Rpdml0eS5Db25uZWN0aXZpdHlFdmVudBIuCgpjcmVhdGVkX2F0GAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIZChFuZXR3b3JrX2ludGVyZmFjZRgFIAEoCSpBChFDb25uZWN0aXZpdHlFdmVudBILCgdVTktOT1dOEAASDQoJQ09OTkVDVEVEEAESEAoMRElTQ09OTkVDVEVEEAJCL1otZ2l0aHViLmNvbS90ZXNsYW1vdG9ycy9mbGVldC10ZWxlbWV0cnkvcHJvdG9zYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * VehicleConnectivity represents connection status change for the vehicle
 *
 * @generated from message telemetry.vehicle_connectivity.VehicleConnectivity
 */
export type VehicleConnectivity = Message<"telemetry.vehicle_connectivity.VehicleConnectivity"> & {
  /**
   * @generated from field: string vin = 1;
   */
  vin: string;

  /**
   * @generated from field: string connection_id = 2;
   */
  connectionId: string;

  /**
   * @generated from field: telemetry.vehicle_connectivity.ConnectivityEvent status = 3;
   */
  status: ConnectivityEvent;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: string network_interface = 5;
   */
  networkInterface: string;
};

/**
 * Describes the message telemetry.vehicle_connectivity.VehicleConnectivity.
 * Use `create(VehicleConnectivitySchema)` to create a new message.
 */
export const VehicleConnectivitySchema: GenMessage<VehicleConnectivity> = /*@__PURE__*/
  messageDesc(file_vehicle_connectivity, 0);

/**
 * ConnectivityEvent represents connection state of the vehicle
 *
 * @generated from enum telemetry.vehicle_connectivity.ConnectivityEvent
 */
export enum ConnectivityEvent {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: CONNECTED = 1;
   */
  CONNECTED = 1,

  /**
   * @generated from enum value: DISCONNECTED = 2;
   */
  DISCONNECTED = 2,
}

/**
 * Describes the enum telemetry.vehicle_connectivity.ConnectivityEvent.
 */
export const ConnectivityEventSchema: GenEnum<ConnectivityEvent> = /*@__PURE__*/
  enumDesc(file_vehicle_connectivity, 0);

