// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file vehicle_metric.proto (package telemetry.vehicle_metrics, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file vehicle_metric.proto.
 */
export const file_vehicle_metric: GenFile = /*@__PURE__*/
  fileDesc("ChR2ZWhpY2xlX21ldHJpYy5wcm90bxIZdGVsZW1ldHJ5LnZlaGljbGVfbWV0cmljcyKBAQoOVmVoaWNsZU1ldHJpY3MSMgoHbWV0cmljcxgBIAMoCzIhLnRlbGVtZXRyeS52ZWhpY2xlX21ldHJpY3MuTWV0cmljEi4KCmNyZWF0ZWRfYXQYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEgsKA3ZpbhgDIAEoCSKNAQoGTWV0cmljEgwKBG5hbWUYASABKAkSOQoEdGFncxgCIAMoCzIrLnRlbGVtZXRyeS52ZWhpY2xlX21ldHJpY3MuTWV0cmljLlRhZ3NFbnRyeRINCgV2YWx1ZRgDIAEoARorCglUYWdzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4AUIvWi1naXRodWIuY29tL3Rlc2xhbW90b3JzL2ZsZWV0LXRlbGVtZXRyeS9wcm90b3NiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * VehicleMetrics is a collection of metrics for a single vehicle.
 *
 * @generated from message telemetry.vehicle_metrics.VehicleMetrics
 */
export type VehicleMetrics = Message<"telemetry.vehicle_metrics.VehicleMetrics"> & {
  /**
   * @generated from field: repeated telemetry.vehicle_metrics.Metric metrics = 1;
   */
  metrics: Metric[];

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 2;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: string vin = 3;
   */
  vin: string;
};

/**
 * Describes the message telemetry.vehicle_metrics.VehicleMetrics.
 * Use `create(VehicleMetricsSchema)` to create a new message.
 */
export const VehicleMetricsSchema: GenMessage<VehicleMetrics> = /*@__PURE__*/
  messageDesc(file_vehicle_metric, 0);

/**
 * Metric is a single metric value with a name, tags, and a value.
 *
 * @generated from message telemetry.vehicle_metrics.Metric
 */
export type Metric = Message<"telemetry.vehicle_metrics.Metric"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: map<string, string> tags = 2;
   */
  tags: { [key: string]: string };

  /**
   * @generated from field: double value = 3;
   */
  value: number;
};

/**
 * Describes the message telemetry.vehicle_metrics.Metric.
 * Use `create(MetricSchema)` to create a new message.
 */
export const MetricSchema: GenMessage<Metric> = /*@__PURE__*/
  messageDesc(file_vehicle_metric, 1);

