name: auto-merge

on:
  pull_request:
    branches: [ dependencies ]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.MERGE_TOKEN }}
          command: squash
          approve: true
          target: patch
